name: Deploy Next.js to Vercel and Database to Vercel
on:
  push: 
    branches:
    -main

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      -name:Checkout repository
       uses:actions/checkout@v3


      -name:Setup Node.js
       uses:actions/setup-node@v3
       with:
       node-version:22.9.0

       -name:Install dependencies
       run:npm install

       -name:Run tests
       run:npm test

      -name:Run Prisma Migrations
       run:npx prisma migrate deploy
       env:
        DATABASE_URL:${{secrets.DATABASE_URL}}

      -name:Build projet
      run:npm run build
      env:  
      DATABASE_URL:${{secrets.DATABASE_URL}}